### ISSUE TITLE
Need to fix severity issues

### ISSUE THREAD

**Issue by mwang840** [mwang840/Mr_Ditkovich_bot#24]
when I did npm audit --force fix, despite node modules fixing the program there were still three vulnerabilities that were shown and will need to fix it because I want it to handle videos from a yt channel without giving viruses to the yt acct profile (package files)

**Comment by cthacker-udel** [comment]
`will need to fix it`, under what evidence do we **need** to fix it? A hypothetical bug does not warrant an issue, only once proven it is happening can it become an issue. Closing for now.
